packages:
  - src
  - scripts

# Remove any "ignoredBuiltDependencies" you had before
# ignoredBuiltDependencies:  # ← delete this whole key if present

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
