name: Auto-Triage and Label
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label new issues
        if: github.event_name == 'issues'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            needs-triage

      - name: Label PRs by environment
        if: github.event_name == 'pull_request'
        run: |
          PR_BRANCH="${{ github.head_ref }}"
          LABEL=""

          if [[ "$PR_BRANCH" == *"staging"* ]]; then
            LABEL="env:staging"
          elif [[ "$PR_BRANCH" == *"preview"* ]]; then
            LABEL="env:preview"
          elif [[ "$PR_BRANCH" == *"prod"* || "$PR_BRANCH" == *"main"* ]]; then
            LABEL="env:prod"
          else
            LABEL="env:local"
          fi

          echo "Applying label: $LABEL"
          gh issue edit ${{ github.event.pull_request.number }} \
            --add-label "$LABEL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
