name: Quick Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to roll back'
        type: choice
        required: true
        options:
          - prod
          - staging
          - preview
        default: prod
      steps_back:
        description: 'How many good releases back? (1 = previous)'
        type: number
        required: true
        default: 1

concurrency:
  group: quick-rollback-${{ github.ref }}
  cancel-in-progress: false

jobs:
  rollback:
    runs-on: ubuntu-latest
    env:
      STEPS_BACK: ${{ inputs.steps_back }}
    steps:
      - name: Compute target directory by env
        id: pick
        run: |
          case "${{ inputs.environment }}" in
            prod)    echo "APP_DIR=${{ secrets.DEPLOY_APP_DIR }}"           >> "$GITHUB_OUTPUT" ;;
            staging) echo "APP_DIR=${{ secrets.DEPLOY_STAGING_APP_DIR }}"   >> "$GITHUB_OUTPUT" ;;
            preview) echo "APP_DIR=${{ secrets.DEPLOY_PREVIEW_APP_DIR }}"   >> "$GITHUB_OUTPUT" ;;
            *)       echo "Unknown env" && exit 1 ;;
          esac

      - name: Roll back on remote host
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          APP_DIR: ${{ steps.pick.outputs.APP_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "
            set -e
            cd \"$APP_DIR\"
            echo 'Current:' && git rev-parse --short HEAD
            # Reset back N commits (safe only if you deploy from main/develop without merges)
            git reset --hard HEAD~${STEPS_BACK}
            git clean -fd
            pnpm install --frozen-lockfile || pnpm install
            pnpm ignored-builds || true
            NODE_ENV=production pnpm run build
            ( command -v pm2 >/dev/null 2>&1 && pm2 reload summitcare || pm2 reload summitcare-staging || pm2 reload summitcare-preview ) \
              || pnpm dlx pm2 start 'pnpm -- run start' --name summitcare
            pnpm dlx pm2 save || true
            echo 'Rolled back to:' && git rev-parse --short HEAD
          "
